package: multiglossar
version: '2.0.0-beta4'
author: Friends Of REDAXO
supportpage: ''
compile: 0

page:
  title: 'translate:glossar'
  perm: multiglossar[general]
  pjax: true
  icon: rex-icon fa-font
  subpages:
        main: { title: 'translate:glossar' }

requires:
  redaxo: '^5.1.0'
